[package]
name = "satz-cli"
version = "0.1.0"
edition = "2024"

[lib]
name = "satz_cli"
path = "src/lib.rs"

[[bin]]
name = "satz"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
satz-core.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
