[package]
name = "satz-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
name = "satz_cli"
path = "src/lib.rs"

[[bin]]
name = "satz"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
rayon.workspace = true
satz-core.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
